<?php
$pageTitle = 'Statut i dokumenta | Микиликс веб развој';
$pageDescription = 'Statut i javna dokumenta Udruženja „Микиликс веб развој" — preuzmite u PDF ili Word formatu.';
$activePage = 'dokumenta';
require __DIR__ . '/includes/header.php';
?>

<section class="subhero"><div class="container"><div class="breadcrumbs"><a href="index.php">Početna</a> / Dokumenta</div><h1>Statut i dokumenta</h1><p class="lead">Javno dostupni akti, rešenja i izveštaji udruženja na jednom mestu.</p></div></section>
<section class="section"><div class="container grid grid-2"><div><span class="eyebrow">Javna dokumenta</span><h2>Transparentan rad udruženja</h2><p>Statut predviđa javnost rada i redovno obaveštavanje članstva i javnosti. Ova stranica je pripremljena za objavljivanje najvažnijih dokumenata.</p><div class="notice">Statut je već dodat u PDF i originalnom Word formatu. Ostala dokumenta su pripremljena kao mesta za naknadni unos.</div></div><div class="doc-list"><div class="doc-row"><div class="doc-icon">PDF</div><div class="doc-info"><strong>Statut Udruženja</strong><small>Usvojen 01.06.2026. • 6 strana</small></div><a class="btn btn-primary btn-sm" href="documents/STATUT.pdf" target="_blank">Otvori</a></div><div class="doc-row"><div class="doc-icon">DOC</div><div class="doc-info"><strong>Statut - original</strong><small>Microsoft Word dokument</small></div><a class="btn btn-outline btn-sm" href="documents/STATUT-original.doc">Preuzmi</a></div><div class="doc-row"><div class="doc-icon">APR</div><div class="doc-info"><strong>Rešenje APR-a</strong><small>Dodati skenirano ili elektronsko rešenje</small></div><a class="btn btn-outline btn-sm disabled" href="#">U pripremi</a></div><div class="doc-row"><div class="doc-icon">GI</div><div class="doc-info"><strong>Godišnji izveštaji</strong><small>Izveštaji o radu i aktivnostima po godinama</small></div><a class="btn btn-outline btn-sm disabled" href="#">U pripremi</a></div><div class="doc-row"><div class="doc-icon">FI</div><div class="doc-info"><strong>Finansijski izveštaji</strong><small>Dokumenta za povećanje transparentnosti rada</small></div><a class="btn btn-outline btn-sm disabled" href="#">U pripremi</a></div></div></div></section>
<section class="section soft"><div class="container"><div class="center"><span class="eyebrow">Registar dokumenata</span><h2>Predložena organizacija objava</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Vrsta dokumenta</th><th>Period</th><th>Datum objave</th><th>Status</th></tr></thead><tbody><tr><td>Statut</td><td>Važeći</td><td>01.06.2026.</td><td>Objavljeno</td></tr><tr><td>Rešenje APR-a</td><td>Važeće</td><td>-</td><td>Dodati dokument</td></tr><tr><td>Godišnji izveštaj</td><td>2026.</td><td>-</td><td>U pripremi</td></tr><tr><td>Finansijski izveštaj</td><td>2026.</td><td>-</td><td>U pripremi</td></tr></tbody></table></div></div></section>

<?php require __DIR__ . '/includes/footer.php'; ?>
