<?php
$page_title       = 'Statut i dokumenta';
$page_description = 'Statut i javna dokumenta Udruženja „Mikiliks veb razvoja" — preuzmite u PDF ili Word formatu.';
require __DIR__ . '/includes/header.php';
?>

<section class="subhero"><div class="container"><div class="breadcrumbs"><a href="index.php">Početna</a> / Dokumenta</div><h1>Statut i dokumenta</h1><p class="lead">Javno dostupni akti, rešenja i izveštaji udruženja na jednom mestu.</p></div></section>
<section class="section"><div class="container grid grid-2"><div><span class="eyebrow">Javna dokumenta</span><h2>Transparentnost i javnost rada</h2><p>Javnost rada jedno je od osnovnih načela našeg Udruženja. Članovima, partnerima i široj javnosti omogućavamo jednostavan pristup najvažnijim dokumentima i informacijama o našem radu.</p><p>Na jednom mestu možete pronaći Statut Udruženja, Rešenje APR-a, godišnje izveštaje i podatke o finansijskim izveštajima.</p><div class="notice">Statut je dostupan u PDF i originalnom Word formatu. Rešenje APR-a, godišnji izveštaj i finansijski izveštaji su javno dostupni ispod.</div></div><div class="doc-list"><div class="doc-row"><div class="doc-icon">PDF</div><div class="doc-info"><strong>Statut Udruženja</strong><small>Usvojen 01.06.2026. • 6 strana</small></div><a class="btn btn-primary btn-sm" href="documents/statut.pdf" target="_blank">Otvori</a></div><div class="doc-row"><div class="doc-icon">DOC</div><div class="doc-info"><strong>Statut 01.06.2026. - original</strong><small>Microsoft Word dokument, bez pečata i potpisa</small></div><a class="btn btn-outline btn-sm" href="documents/statut.docx">Preuzmi</a></div><div class="doc-row"><div class="doc-icon">APR</div><div class="doc-info"><strong>Rešenje APR-a</strong><small>Doneto 17.06.2026.</small></div><a class="btn btn-primary btn-sm" href="documents/resenje.pdf" target="_blank">Otvori</a></div><div class="doc-row"><div class="doc-icon">GI</div><div class="doc-info"><strong>Godišnji izveštaji</strong><small>Izveštaj o radu i aktivnostima za 2025. usvojen 22.12.2025.</small></div><a class="btn btn-outline btn-sm" href="documents/godisnji_izvestaj_2025.docx">Preuzmi</a></div><div class="doc-row"><div class="doc-icon">FI</div><div class="doc-info"><strong>Finansijski izveštaji</strong><small>Javna pretraga APR-a — izveštaji 2022–2025.</small></div><a class="btn btn-outline btn-sm" href="https://fin.apr.gov.rs/JavnaPretraga/FiDetails?mbr=28185685&rnd=38ab8983-149d-4728-832f-974668b2d16a&tknfv=99dcf6ec9-8f6d-4d0e-9ddd-cf19448a03322n1" target="_blank" rel="noopener noreferrer">Otvori na APR</a></div></div></div></section>
<section class="section soft"><div class="container"><div class="center"><span class="eyebrow">Potvrde</span><h2>Dodatne potvrde APR-a</h2><p class="lead">Potvrde o predatim finansijskim izveštajima, po godinama.</p></div><div class="doc-list" style="max-width:640px;margin:0 auto"><div class="doc-row"><div class="doc-icon">APR</div><div class="doc-info"><strong>Potvrda o finansijskim izveštajima 2025.</strong><small>Izveštajni period: 01.01.2025 – 31.12.2025. · Objavljeno: 03.03.2026.</small></div><a class="btn btn-outline btn-sm" href="https://fin.apr.gov.rs/JavnaPretraga/Home/DownloadDocumentFile?barcode=7100236440007&xrnd=mPJg6ebVyR_AhleBQ67MjfUh6Wsw893IhDxeQaC6Wdw" target="_blank" rel="noopener noreferrer">Preuzmi</a></div><div class="doc-row"><div class="doc-icon">APR</div><div class="doc-info"><strong>Potvrda o finansijskim izveštajima 2024.</strong><small>Izveštajni period: 01.01.2024 – 31.12.2024. · Objavljeno: 13.03.2025.</small></div><a class="btn btn-outline btn-sm" href="https://fin.apr.gov.rs/JavnaPretraga/Home/DownloadDocumentFile?barcode=7100211641825&xrnd=bjcGGgwLmjsCqoL4b3A1JVQo1o7zISyVh4QoSvgRUGU" target="_blank" rel="noopener noreferrer">Preuzmi</a></div><div class="doc-row"><div class="doc-icon">APR</div><div class="doc-info"><strong>Potvrda o finansijskim izveštajima 2023.</strong><small>Izveštajni period: 01.01.2023 – 31.12.2023. · Objavljeno: 09.03.2024.</small></div><a class="btn btn-outline btn-sm" href="https://fin.apr.gov.rs/JavnaPretraga/Home/DownloadDocumentFile?barcode=7100186112955&xrnd=dd7woG0m3plsWJCH6dqE6wDNZsWay62vEWs2IXAHwG0" target="_blank" rel="noopener noreferrer">Preuzmi</a></div><div class="doc-row"><div class="doc-icon">APR</div><div class="doc-info"><strong>Potvrda o finansijskim izveštajima 2022.</strong><small>Izveštajni period: 01.01.2022 – 31.12.2022. · Objavljeno: 15.03.2023.</small></div><a class="btn btn-outline btn-sm" href="https://fin.apr.gov.rs/JavnaPretraga/Home/DownloadDocumentFile?barcode=7100162630251&xrnd=o234tNEs3JKtlx588fGv7MohjmabNaRTcWVJMonKjGE" target="_blank" rel="noopener noreferrer">Preuzmi</a></div></div></div></section>
<section class="section soft"><div class="container"><div class="center"><span class="eyebrow">Registar dokumenata</span><h2>Predložena organizacija objava</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Vrsta dokumenta</th><th>Period</th><th>Datum objave</th><th>Status</th></tr></thead><tbody><tr><td>Statut</td><td>Važeći</td><td>01.06.2026.</td><td>Objavljeno</td></tr><tr><td>Rešenje APR-a</td><td>Važeće</td><td>17.06.2026.</td><td>Objavljeno</td></tr><tr><td>Godišnji izveštaj</td><td>2025.</td><td>22.12.2025.</td><td>Objavljeno</td></tr><tr><td>Finansijski izveštaj</td><td>2022–2025.</td><td>03.03.2026.</td><td>Objavljeno</td></tr></tbody></table></div></div></section>

<?php require __DIR__ . '/includes/footer.php'; ?>
