<?php
$pageTitle = 'Donacije i podrška | Микиликс веб развој';
$pageDescription = 'Kako podržati rad Udruženja „Микиликс веб развој" — donacije, sponzorstva i volontiranje.';
$activePage = 'donacije';
require __DIR__ . '/includes/header.php';
?>

<section class="subhero"><div class="container"><div class="breadcrumbs"><a href="index.php">Početna</a> / Donacije i podrška</div><h1>Donacije i podrška</h1><p class="lead">Načini na koje građani, organizacije i partneri mogu podržati obrazovne i digitalne aktivnosti udruženja.</p></div></section>
<section class="section"><div class="container grid grid-2"><div><span class="eyebrow">Podržite naš rad</span><h2>Podrška koja se pretvara u znanje i korisne projekte</h2><p>Udruženje može pribavljati sredstva od dobrovoljnih priloga, donacija, poklona, sponzorstava, konkursa, fondova, projekata i na druge zakonom dozvoljene načine.</p><div class="check-list"><div class="check"><i>✓</i><span>Podrška organizaciji edukacija i radionica</span></div><div class="check"><i>✓</i><span>Nabavka opreme i obrazovnih materijala</span></div><div class="check"><i>✓</i><span>Razvoj besplatnih digitalnih sadržaja</span></div><div class="check"><i>✓</i><span>Sufinansiranje projekata od javnog interesa</span></div></div></div><div class="content-card"><span class="eyebrow">Podaci za uplatu</span><h3>Udruženje „Микиликс веб развој“</h3><p><strong>PIB:</strong> <em style="color:var(--muted);font-style:normal">[unesite PIB]</em><br><strong>Matični broj:</strong> <em style="color:var(--muted);font-style:normal">[unesite matični broj]</em><br><strong>Sedište:</strong> Kragujevac, Srbija</p><div class="admin-note">PIB, matični broj i broj računa nisu bili navedeni u dostavljenim dokumentima. Unesite tačne podatke iz rešenja APR-a i banke pre objavljivanja ove stranice.</div><p style="margin-top:20px"><strong>Svrha uplate:</strong> Donacija za programske aktivnosti udruženja</p><a class="btn btn-primary" href="kontakt.php">Kontakt za donacije →</a></div></div></section>
<section class="section soft"><div class="container"><div class="center"><span class="eyebrow">Drugi načini podrške</span><h2>Možete pomoći i bez novčane donacije</h2></div><div class="grid grid-3 cards"><div class="service-card"><h3>Volontiranje</h3><p>Uključite se kao predavač, mentor, organizator, autor materijala ili tehnička podrška.</p></div><div class="service-card"><h3>Oprema i resursi</h3><p>Podržite programe donacijom opreme, licenci, prostora, štampe ili drugih potrebnih resursa.</p></div><div class="service-card"><h3>Partnerski projekat</h3><p>Predložite zajedničku aktivnost u oblasti obrazovanja, nauke, digitalnog razvoja ili veb tehnologija.</p></div></div></div></section>

<?php require __DIR__ . '/includes/footer.php'; ?>
