<?php
$pageTitle = 'Kursevi i edukacije | Микиликс веб развој';
$pageDescription = 'Kursevi, radionice, seminari i stručno usavršavanje koje organizuje Udruženje „Микиликс веб развој".';
$activePage = 'edukacije';
require __DIR__ . '/includes/header.php';
?>

<section class="subhero"><div class="container"><div class="breadcrumbs"><a href="index.php">Početna</a> / Edukacije</div><h1>Kursevi i edukacije</h1><p class="lead">Programi stručnog usavršavanja, radionice, seminari, kursevi i drugi oblici formalnog i neformalnog obrazovanja.</p></div></section>
<section class="section"><div class="container"><div class="center"><span class="eyebrow">Programi</span><h2>Učenje prilagođeno savremenim potrebama</h2></div><div class="grid grid-3 cards"><div class="service-card"><div class="icon-box"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3"><rect x="7" y="8" width="34" height="25" rx="3"/><path d="M17 41h14M24 33v8M16 17l-5 4 5 4m16-8 5 4-5 4m-5-10-6 12"/></svg></div><h3>Digitalna pismenost</h3><p>Računar, internet, elektronski servisi, bezbednost, komunikacija i organizacija digitalnih dokumenata.</p></div><div class="service-card"><div class="icon-box"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3"><circle cx="24" cy="24" r="18"/><path d="M6 24h36M24 6c6 5 9 11 9 18s-3 13-9 18c-6-5-9-11-9-18S18 11 24 6Z"/></svg></div><h3>Veb i programiranje</h3><p>Osnove izrade sajtova, WordPress, HTML i CSS, rad sa sadržajem i uvod u računarsko programiranje.</p></div><div class="service-card"><div class="icon-box"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 18 24 8l19 10-19 10L5 18Z"/><path d="M12 23v12c8 6 16 6 24 0V23"/><path d="M43 18v14"/></svg></div><h3>Obuke za ustanove</h3><p>Programi po meri škola, organizacija i privrednih subjekata, sa praktičnim zadacima i podrškom.</p></div><div class="service-card"><div class="icon-box"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3"><circle cx="20" cy="20" r="12"/><path d="m29 29 12 12M15 20h10M20 15v10"/></svg></div><h3>Naučne radionice</h3><p>Aktivnosti iz prirodnih, tehničkih i informacionih nauka za decu, mlade i zainteresovane građane.</p></div><div class="service-card"><div class="icon-box"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3"><path d="M8 10h12l4 5h16v25H8z"/><path d="M15 26h18M15 32h12"/></svg></div><h3>Stručni skupovi</h3><p>Seminari, tribine, konferencije, savetovanja i razmena iskustava sa stručnjacima i partnerima.</p></div><div class="service-card"><div class="icon-box"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3"><path d="m4 20 10-8 10 7-9 9zM44 20l-10-8-10 7 9 9z"/><path d="m16 27 6 6c2 2 4 2 6 0l5-5M10 32l7 7c2 2 4 2 6 0l2-2"/></svg></div><h3>Mentorska podrška</h3><p>Savetodavna pomoć pri razvoju obrazovnih, digitalnih i veb projekata.</p></div></div></div></section>
<section class="section soft"><div class="container grid grid-2"><div><span class="eyebrow">Kalendar</span><h2>Naredne aktivnosti</h2><p>Po objavljivanju termina, ovde se prikazuju naziv aktivnosti, datum, trajanje, mesto ili online link, predavač, broj mesta i način prijave.</p><div class="admin-note">Trenutno nema objavljenih termina. Stranica je spremna za unos kalendara edukacija.</div></div><div class="content-card"><h3>Prijavite interesovanje</h3><form class="form" data-demo-form><div class="field"><label for="edu-name">Ime i prezime</label><input id="edu-name" required></div><div class="field"><label for="edu-email">E-mail</label><input id="edu-email" type="email" required></div><div class="field"><label for="edu-topic">Oblast interesovanja</label><select id="edu-topic"><option>Digitalna pismenost</option><option>Veb razvoj</option><option>Programiranje</option><option>Obuka za organizaciju</option><option>Drugo</option></select></div><button class="btn btn-primary" type="submit">Pošalji interesovanje</button><div class="notice form-message" style="display:none"></div></form></div></div></section>

<?php require __DIR__ . '/includes/footer.php'; ?>
