<?php
$page_title       = 'Početna';
$page_description = 'Udruženje „Микиликс веб развој" (Kragujevac) — obrazovanje, digitalna pismenost, informacione tehnologije i veb razvoj, u skladu sa Statutom udruženja.';
require __DIR__ . '/includes/header.php';
?>

<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">Obrazovanje • IT • Digitalni razvoj</span><h1>Znanje koje pokreće <span>digitalno društvo</span></h1><p>Udruženje „Микиликс веб развој“ povezuje obrazovanje, nauku i savremene tehnologije kroz edukacije, razvoj veb rešenja, digitalne projekte i saradnju od javnog interesa.</p><div class="hero-actions"><a class="btn btn-primary" href="projekti.php">Istražite naše aktivnosti <span class="arrow">→</span></a><a class="btn btn-light" href="o-nama.php">Upoznajte udruženje</a></div><div class="hero-tags"><span class="tag">Digitalna pismenost</span><span class="tag">Veb razvoj</span><span class="tag">Edukacije</span><span class="tag">Nauka i istraživanje</span></div></div><div class="hero-art"><img src="assets/img/hero-illustration.svg" alt="Ilustracija digitalnog obrazovanja i veb razvoja"></div></div></section>
<div class="floating-strip"><div class="container strip"><div class="strip-item"><div class="strip-num">2026.</div><div class="strip-label">godina usvajanja važećeg Statuta</div></div><div class="strip-item"><div class="strip-num">13</div><div class="strip-label">programskih pravaca navedenih u Statutu</div></div><div class="strip-item"><div class="strip-num">RS</div><div class="strip-label">delovanje na teritoriji Republike Srbije</div></div></div></div>
<section class="section"><div class="container about-grid"><div><img src="assets/img/about-illustration.svg" alt="Vizuelni prikaz udruženja"></div><div><span class="eyebrow">O udruženju</span><h2>Spajamo obrazovanje, tehnologiju i društveni napredak</h2><p>Udruženje je osnovano radi unapređenja obrazovanja i vaspitanja, nauke, informatičke i digitalne pismenosti, razvoja i primene informacionih tehnologija, stručnog usavršavanja građana i razvoja digitalnog društva.</p><div class="about-card-list"><div class="mini-card"><strong>Misija</strong><span>Znanje i savremene tehnologije učiniti dostupnijim građanima.</span></div><div class="mini-card"><strong>Vizija</strong><span>Društvo u kome digitalne veštine podstiču obrazovanje i razvoj.</span></div></div><div class="check-list"><div class="check"><i>✓</i><span>Formalno i neformalno obrazovanje, seminari, kursevi i radionice</span></div><div class="check"><i>✓</i><span>Razvoj veb prezentacija, aplikacija i digitalnih platformi</span></div><div class="check"><i>✓</i><span>Projekti, istraživanje, publikacije i stručna podrška</span></div></div><a class="btn btn-primary" href="o-nama.php">Više o nama <span class="arrow">→</span></a></div></div></section>
<section class="section soft"><div class="container"><div class="center"><span class="eyebrow">Oblasti rada</span><h2>Šta radimo</h2><p class="lead">Programske oblasti zasnovane su na ciljevima i aktivnostima navedenim u Statutu udruženja.</p></div><div class="grid grid-3 cards">
<div class="service-card"><div class="icon-box"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3"><path d="M5 18 24 8l19 10-19 10L5 18Z"/><path d="M12 23v12c8 6 16 6 24 0V23"/><path d="M43 18v14"/></svg></div><h3>Edukacije i obuke</h3><p>Kursevi, radionice, seminari, stručni skupovi, predavanja i drugi oblici učenja za decu, mlade i odrasle.</p><a class="more" href="edukacije.php">Saznajte više →</a></div>
<div class="service-card"><div class="icon-box"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3"><rect x="7" y="8" width="34" height="25" rx="3"/><path d="M17 41h14M24 33v8M16 17l-5 4 5 4m16-8 5 4-5 4m-5-10-6 12"/></svg></div><h3>Digitalna pismenost</h3><p>Razvoj praktičnih digitalnih veština, informatičke pismenosti i bezbedne primene savremenih alata.</p><a class="more" href="projekti.php">Saznajte više →</a></div>
<div class="service-card"><div class="icon-box"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3"><circle cx="24" cy="24" r="18"/><path d="M6 24h36M24 6c6 5 9 11 9 18s-3 13-9 18c-6-5-9-11-9-18S18 11 24 6Z"/></svg></div><h3>Veb tehnologije</h3><p>Izrada, razvoj i održavanje internet prezentacija, platformi, aplikacija i edukativnih digitalnih sadržaja.</p><a class="more" href="portfolio.php">Pogledajte portfolio →</a></div>
<div class="service-card"><div class="icon-box"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3"><circle cx="20" cy="20" r="12"/><path d="m29 29 12 12M15 20h10M20 15v10"/></svg></div><h3>Nauka i istraživanje</h3><p>Prikupljanje, analiza i objavljivanje podataka i rezultata važnih za obrazovanje, nauku i digitalni razvoj.</p><a class="more" href="blog.php">Istražite sadržaje →</a></div>
<div class="service-card"><div class="icon-box"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3"><path d="M8 10h12l4 5h16v25H8z"/><path d="M15 26h18M15 32h12"/></svg></div><h3>Projekti i publikacije</h3><p>Priprema i realizacija domaćih i međunarodnih projekata, priručnika, biltena i elektronskih publikacija.</p><a class="more" href="projekti.php">Naši projekti →</a></div>
<div class="service-card"><div class="icon-box"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="3"><path d="m4 20 10-8 10 7-9 9zM44 20l-10-8-10 7 9 9z"/><path d="m16 27 6 6c2 2 4 2 6 0l5-5M10 32l7 7c2 2 4 2 6 0l2-2"/></svg></div><h3>Saradnja i podrška</h3><p>Stručna i savetodavna saradnja sa ustanovama, organizacijama, udruženjima, privredom i građanima.</p><a class="more" href="kontakt.php">Pokrenite saradnju →</a></div>
</div></div></section>
<section class="section"><div class="container"><div class="process-wrap"><span class="eyebrow">Način rada</span><h2>Od ideje do korisnog rezultata</h2><div class="steps"><div class="step"><div class="step-num">01</div><h3>Prepoznajemo potrebu</h3><p>Razgovaramo sa zajednicom, ustanovama i partnerima o konkretnim obrazovnim i digitalnim izazovima.</p></div><div class="step"><div class="step-num">02</div><h3>Pripremamo program</h3><p>Definišemo ciljeve, aktivnosti, učesnike, potrebne resurse i merljive rezultate.</p></div><div class="step"><div class="step-num">03</div><h3>Realizujemo aktivnosti</h3><p>Sprovodimo obuke, projekte, razvoj digitalnih rešenja, istraživanja ili objavljivanje materijala.</p></div><div class="step"><div class="step-num">04</div><h3>Delimo znanje</h3><p>Objavljujemo rezultate, unapređujemo program i podstičemo dalju primenu stečenih znanja.</p></div></div></div></div></section>
<section class="section soft"><div class="container"><div class="center"><span class="eyebrow">Programske oblasti</span><h2>Istaknute aktivnosti</h2><p class="lead">Predložene celine koje mogu da predstavljaju aktuelne i buduće projekte udruženja.</p></div><div class="grid grid-3 projects"><article class="project-card"><div class="project-image"><img src="assets/img/project-digital.svg" alt="Digitalna pismenost"></div><div class="project-body"><div class="project-kicker">Obrazovni program</div><h3>Digitalna pismenost za sve</h3><p>Praktične radionice za sigurnije i kvalitetnije korišćenje računara, interneta i digitalnih servisa.</p></div></article><article class="project-card"><div class="project-image"><img src="assets/img/project-web.svg" alt="Veb razvoj"></div><div class="project-body"><div class="project-kicker">Razvojni program</div><h3>Veb podrška organizacijama</h3><p>Podrška u izradi prezentacija, platformi, formi i digitalnih procesa koji olakšavaju rad organizacija.</p></div></article><article class="project-card"><div class="project-image"><img src="assets/img/project-edu.svg" alt="Edukacije"></div><div class="project-body"><div class="project-kicker">Stručno usavršavanje</div><h3>Radionice i stručne obuke</h3><p>Programi usmereni na savremene nastavne metode, digitalne alate, programiranje i razvoj kompetencija.</p></div></article></div><div class="center" style="margin-top:38px"><a class="btn btn-primary" href="projekti.php">Svi projekti i aktivnosti →</a></div></div></section>
<section class="section-sm stats-band"><div class="container stats"><div class="stat"><strong>3</strong><span>ključne oblasti: obrazovanje, nauka i IT</span></div><div class="stat"><strong>13</strong><span>pravaca delovanja u Statutu</span></div><div class="stat"><strong>2</strong><span>organa udruženja prema Statutu</span></div><div class="stat"><strong>1</strong><span>zajednički cilj: razvoj znanja</span></div></div></section>
<section class="section"><div class="container"><div class="center"><span class="eyebrow">Saradnja</span><h2>Partneri i saradnici</h2><p class="lead">Prostor za logotipe obrazovnih ustanova, institucija, kompanija, udruženja i organizacija sa kojima se realizuju aktivnosti.</p></div><div class="partner-row"><span class="partner">Obrazovne ustanove</span><span class="partner">Naučne institucije</span><span class="partner">Lokalna samouprava</span><span class="partner">Privredni subjekti</span><span class="partner">Udruženja građana</span></div></div></section>
<section class="section soft"><div class="container"><div class="center"><span class="eyebrow">Vesti i obaveštenja</span><h2>Najnovije iz udruženja</h2></div><div class="grid grid-3 cards"><article class="news-card"><div class="news-top"><span class="news-date">01. jun 2026.</span></div><div class="news-body"><div class="news-meta">Dokumenta</div><h3>Usvojen novi Statut udruženja</h3><p>Na Skupštini održanoj u Kragujevcu usvojen je novi Statut kojim su proširene oblasti rada i ciljevi.</p><a class="more" href="dokumenta.php">Pogledajte dokument →</a></div></article><article class="news-card"><div class="news-top"><span class="news-date">Članstvo</span></div><div class="news-body"><div class="news-meta">Obaveštenje</div><h3>Prijava za članstvo</h3><p>Na sajtu je dostupna online forma za građane koji prihvataju ciljeve i Statut udruženja.</p><a class="more" href="clanstvo.php">Popunite pristupnicu →</a></div></article><article class="news-card"><div class="news-top"><span class="news-date">U pripremi</span></div><div class="news-body"><div class="news-meta">Aktivnosti</div><h3>Kalendar edukacija i radionica</h3><p>Ovaj prostor je namenjen objavljivanju narednih kurseva, radionica, seminara i drugih aktivnosti.</p><a class="more" href="edukacije.php">Pogledajte programe →</a></div></article></div></div></section>
<section class="section"><div class="container faq-grid"><div><span class="eyebrow">Česta pitanja</span><h2>Informacije za članove i saradnike</h2><p>Osnovni odgovori zasnovani na Statutu. Za posebna pitanja obratite se udruženju.</p><a class="btn btn-outline" href="kontakt.php">Postavite pitanje</a></div><div><div class="faq-item open"><button class="faq-q">Ko može postati član? <span>＋</span></button><div class="faq-a">Član može biti lice koje prihvata ciljeve Udruženja i Statut i podnese prijavu za učlanjenje. Za maloletna lica primenjuju se uslovi saglasnosti zakonskog zastupnika navedeni u Statutu.</div></div><div class="faq-item"><button class="faq-q">Kako se prijavljuje članstvo? <span>＋</span></button><div class="faq-a">Prijava se može pripremiti kroz online pristupnicu na sajtu, a konačna procedura prijema sprovodi se u skladu sa važećim Statutom i odlukama organa Udruženja.</div></div><div class="faq-item"><button class="faq-q">Sa kim Udruženje može sarađivati? <span>＋</span></button><div class="faq-a">Sa obrazovnim ustanovama, naučnim institucijama, privrednim subjektima, državnim organima, drugim udruženjima i organizacijama u zemlji i inostranstvu.</div></div><div class="faq-item"><button class="faq-q">Gde mogu da preuzmem Statut? <span>＋</span></button><div class="faq-a">Statut je dostupan u PDF formatu na stranici Dokumenta.</div></div></div></div></section>
<section class="section-sm"><div class="container"><div class="cta"><div><span class="eyebrow">Pridružite se</span><h2>Zajedno gradimo prostor za znanje, digitalne veštine i nove ideje.</h2></div><a class="btn btn-primary" href="clanstvo.php">Postani član →</a></div></div></section>

<?php require __DIR__ . '/includes/footer.php'; ?>
