<?php
$pageTitle = 'Kontakt | Микиликс веб развој';
$pageDescription = 'Kontakt podaci i forma za pitanja, saradnju i prijave upućene Udruženju „Микиликс веб развој" iz Kragujevca.';
$activePage = 'kontakt';
require __DIR__ . '/includes/header.php';
?>

<section class="subhero"><div class="container"><div class="breadcrumbs"><a href="index.php">Početna</a> / Kontakt</div><h1>Kontakt</h1><p class="lead">Pošaljite pitanje, predlog za saradnju, prijavu za edukaciju ili informacije o projektu.</p></div></section>
<section class="section"><div class="container contact-grid"><div><span class="eyebrow">Kontakt podaci</span><h2>Razgovarajmo o idejama i saradnji</h2><div class="contact-box"><div class="doc-icon">⌖</div><div><strong>Adresa sedišta</strong><span>Kragujevac, Srbija</span></div></div><div class="contact-box"><div class="doc-icon">@</div><div><strong>E-mail</strong><a href="mailto:info@vas-domen.rs">info@vas-domen.rs</a></div></div><div class="contact-box"><div class="doc-icon">☎</div><div><strong>Telefon</strong><span style="color:var(--muted)">Broj još nije objavljen</span></div></div><div class="contact-box"><div class="doc-icon">ID</div><div><strong>Podaci udruženja</strong><span>PIB: <em style="color:var(--muted);font-style:normal">[unesite PIB]</em><br>Matični broj: <em style="color:var(--muted);font-style:normal">[unesite matični broj]</em></span></div></div></div><div class="admin-note" style="margin-top:14px">Napomena za administraciju sajta: telefon, PIB i matični broj nisu bili navedeni u dostavljenim dokumentima. Unesite tačne podatke iz rešenja APR-a pre objavljivanja sajta.</div><div class="content-card"><span class="eyebrow">Kontakt forma</span><h2 style="font-size:2rem">Pošaljite poruku</h2><form class="form" data-demo-form><div class="grid grid-2"><div class="field"><label for="contact-name">Ime i prezime</label><input id="contact-name" required></div><div class="field"><label for="contact-email">E-mail</label><input id="contact-email" type="email" required></div></div><div class="field"><label for="subject">Tema</label><select id="subject"><option>Opšte pitanje</option><option>Članstvo</option><option>Edukacije</option><option>Projekti i saradnja</option><option>Donacije</option></select></div><div class="field"><label for="message">Poruka</label><textarea id="message" required></textarea></div><label style="display:flex;gap:9px;align-items:flex-start;font-size:.86rem"><input type="checkbox" required style="margin-top:6px"> Saglasan/na sam sa obradom podataka u svrhu odgovora na poruku.</label><button class="btn btn-primary" type="submit">Pošalji poruku</button><div class="notice form-message" style="display:none"></div></form></div></div></section>
<section class="section soft"><div class="container"><div class="center"><span class="eyebrow">Lokacija</span><h2>Sedište udruženja</h2></div><div class="map"><div class="map-pin"><i></i></div></div><p class="center" style="margin-top:18px">Kragujevac, Srbija</p></div></section>

<?php require __DIR__ . '/includes/footer.php'; ?>
