<?php
$page_title       = 'Kontakt';
$page_description = 'Kontakt podaci i forma za pitanja, saradnju i prijave upućene Udruženju „Mikiliks veb razvoja" iz Kragujevca.';
require __DIR__ . '/includes/header.php';
?>

<section class="subhero"><div class="container"><div class="breadcrumbs"><a href="index.php">Početna</a> / Kontakt</div><h1>Kontakt</h1><p class="lead">Pošaljite pitanje, predlog za saradnju, prijavu za edukaciju ili informacije o projektu.</p></div></section>
<section class="section"><div class="container contact-grid"><div><span class="eyebrow">Kontakt podaci</span><h2>Razgovarajmo o idejama i saradnji</h2><div class="contact-box"><div class="doc-icon">⌖</div><div><strong>Adresa sedišta</strong><span><?= e($site['adresa']) ?></span></div></div><div class="contact-box"><div class="doc-icon">@</div><div><strong>E-mail</strong><a href="mailto:<?= e($site['email']) ?>"><?= e($site['email']) ?></a></div></div><div class="contact-box"><div class="doc-icon">🕐</div><div><strong>Radno vreme</strong><span><?= e($site['radno_vreme']) ?></span></div></div><div class="contact-box"><div class="doc-icon">☎</div><div><strong>Telefon</strong><a href="tel:<?= e($site['telefon_tel']) ?>"><?= e($site['telefon']) ?></a></div></div><div class="contact-box"><div class="doc-icon">🏢</div><div><strong>Podaci udruženja</strong><span>PIB: <?= e($site['pib']) ?><br>Matični broj: <?= e($site['mb']) ?></span></div></div><?php $aktivne_mreze = array_filter($drustvene_mreze); if ($aktivne_mreze): ?><div class="contact-box"><div class="doc-icon">🔗</div><div><strong>Društvene mreže</strong><div class="social-icons"><?php foreach ($aktivne_mreze as $mreza => $link): ?><a href="<?= e($link) ?>" target="_blank" rel="noopener noreferrer" aria-label="<?= e(naziv_mreze($mreza)) ?>"><?= ikonica_mreze($mreza) ?></a><?php endforeach; ?></div></div></div><?php endif; ?></div><div class="content-card"><span class="eyebrow">Kontakt forma</span><h2 style="font-size:2rem">Pošaljite poruku</h2><form class="form" data-demo-form><div class="field"><label for="contact-name">Ime i prezime</label><input id="contact-name" required></div><div class="grid grid-2"><div class="field"><label for="contact-email">E-mail</label><input id="contact-email" type="email" required></div><div class="field"><label for="contact-phone">Telefon</label><input id="contact-phone" type="tel"></div></div><div class="field"><label for="subject">Tema</label><select id="subject" required><option value="" disabled selected>Izaberite temu</option><option>Opšte pitanje</option><option>Članstvo</option><option>Edukacije</option><option>Projekti i saradnja</option><option>Donacije</option></select></div><div class="field"><label for="message-title">Naslov poruke</label><input id="message-title" required></div><div class="field"><label for="message">Poruka</label><textarea id="message"></textarea></div><label style="display:flex;gap:9px;align-items:flex-start;font-size:.86rem"><input type="checkbox" required style="margin-top:6px"> Saglasan/na sam sa obradom podataka u svrhu odgovora na poruku.</label><button class="btn btn-primary" type="submit">Pošalji poruku</button><div class="notice form-message" style="display:none"></div></form></div></div></section>
<?php
$map_upit  = urlencode('Udruženje ' . $site['naziv'] . ', ' . $site['adresa']);
$map_embed = 'https://www.google.com/maps?q=' . $map_upit . '&output=embed';
$map_link  = 'https://www.google.com/maps/search/?api=1&query=' . $map_upit;
?>
<section class="section soft"><div class="container"><div class="center"><span class="eyebrow">Lokacija</span><h2>Sedište udruženja</h2></div><div class="map"><iframe src="<?= e($map_embed) ?>" loading="lazy" referrerpolicy="no-referrer-when-downgrade" title="Lokacija Udruženja Mikiliks veb razvoj na mapi"></iframe></div><p class="center" style="margin-top:18px"><?= e($site['adresa']) ?></p><p class="center"><a class="btn btn-outline btn-sm" href="<?= e($map_link) ?>" target="_blank" rel="noopener noreferrer">Otvori u Google Maps <span class="arrow">→</span></a></p></div></section>

<?php require __DIR__ . '/includes/footer.php'; ?>
