<?php
$page_title       = 'O nama';
$page_description = 'Ko smo, koje ciljeve ostvarujemo i kako je organizovano Udruženje „Mikiliks veb razvoja" prema važećem Statutu.';
require __DIR__ . '/includes/header.php';
?>

<section class="subhero"><div class="container"><div class="breadcrumbs"><a href="index.php">Početna</a> / O nama</div><h1>O nama</h1><p class="lead">Ko smo, zašto postojimo i na koji način ostvarujemo ciljeve u oblasti obrazovanja, nauke i informacionih tehnologija.</p></div></section>
<section class="section"><div class="container about-grid"><div><span class="eyebrow">Ko smo</span><h2>Dobrovoljno, nevladino i neprofitno udruženje</h2><p>Udruženje „Mikiliks veb razvoja“ okuplja nastavnike, stručne saradnike, prosvetne radnike, stručnjake iz oblasti informacionih tehnologija i druge građane zainteresovane za obrazovanje, nauku i digitalni razvoj.</p><p>Delatnost ostvaruje na teritoriji Republike Srbije, sa sedištem u Kragujevcu.</p><div class="pill-list"><span class="pill">Obrazovanje i vaspitanje</span><span class="pill">Nauka</span><span class="pill">Informacione tehnologije</span><span class="pill">Veb tehnologije</span><span class="pill">Programiranje</span><span class="pill">Digitalna pismenost</span></div></div><div><img src="assets/img/about-illustration.svg" alt="O udruženju"></div></div></section>
<section class="section soft"><div class="container grid grid-2"><div class="content-card"><span class="eyebrow">Misija</span><h2 style="font-size:2rem">Znanje pretvaramo u praktične mogućnosti</h2><p>Naša misija je unapređenje znanja, veština i kompetencija građana kroz edukacije, stručnu podršku, istraživanje, razvoj digitalnih rešenja i saradnju sa institucijama i zajednicom.</p></div><div class="content-card"><span class="eyebrow">Vizija</span><h2 style="font-size:2rem">Savremeno, uključivo i digitalno društvo</h2><p>Težimo društvu u kome su kvalitetno obrazovanje, digitalna pismenost, inovacije i savremene tehnologije dostupni i primenjivi u svakodnevnom životu i radu.</p></div></div></section>
<section class="section"><div class="container"><div class="center"><span class="eyebrow">Istorijat</span><h2>Razvoj udruženja</h2></div><div class="timeline"><div class="timeline-item"><span class="timeline-dot"></span><time>1. oktobar 2015.</time><h3>Osnivanje udruženja</h3><p>Udruženje je osnovano pod nazivom „Programiraj svoju budućnost“ (Code Your Future), sa sedištem u Topoli.</p></div><div class="timeline-item"><span class="timeline-dot"></span><time>12. maj 2021.</time><h3>Izbor novog zastupnika Udruženja</h3><p>Za novog zastupnika udruženja izabran je Milan Nedeljković.</p></div><div class="timeline-item"><span class="timeline-dot"></span><time>2. januar 2024.</time><h3>Promena naziva i sedišta</h3><p>Udruženje menja naziv u „Mikiliks veb razvoj“ (Mikiliks veb development), sa novim sedištem u Kragujevcu, u ulici Kralja Milana IV 13/21.</p></div><div class="timeline-item"><span class="timeline-dot"></span><time>1. jun 2026.</time><h3>Usvajanje novog Statuta</h3><p>Prošireni su ciljevi i aktivnosti u oblastima obrazovanja, nauke, istraživanja, razvoja digitalnih platformi, publikacija i saradnje. Statut je dostupan <a href="documents/STATUT.pdf" style="color:var(--primary-dark);font-weight:700">ovde u PDF formatu</a>.</p></div></div></div></section>
<section class="section soft"><div class="container"><div class="center"><span class="eyebrow">Organi udruženja</span><h2>Upravljanje i zastupanje</h2><p class="lead">Prema članu 8. aktuelnog Statuta, organi Udruženja su Skupština i zastupnik Udruženja.</p></div><div class="grid grid-2 cards"><div class="team-card"><div class="avatar">S</div><h3>Skupština</h3><p>Čine je svi članovi. Donosi Statut, usvaja finansijske izveštaje, bira i opoziva zastupnika i odlučuje o ključnim pitanjima.</p></div><div class="team-card"><div class="avatar">MN</div><h3>Milan Nedeljković</h3><p><strong>Zastupnik Udruženja</strong></p><p>Rukovodi radom Udruženja između sednica Skupštine i, prema članu 12. Statuta, između ostalog:</p><ul style="margin:10px 0 0 18px;color:var(--muted);font-size:.92rem;line-height:1.7"><li>organizuje redovno obavljanje delatnosti Udruženja;</li><li>donosi finansijske odluke i priprema finansijski plan;</li><li>poverava posebne poslove pojedinim članovima;</li><li>predlaže Skupštini izmene i dopune Statuta i druga opšta akta.</li></ul></div></div></div></section>
<section class="section"><div class="container"><div class="center"><span class="eyebrow">Ciljevi</span><h2>Šta želimo da ostvarimo</h2></div><div class="grid grid-3 cards"><div class="service-card"><h3>Unapređenje obrazovanja</h3><p>Podizanje kvaliteta obrazovanja, stručnog usavršavanja i savremenih metoda učenja.</p></div><div class="service-card"><h3>Razvoj digitalnih kompetencija</h3><p>Informatička i digitalna pismenost za decu, mlade, odrasle i organizacije.</p></div><div class="service-card"><h3>Primena tehnologije</h3><p>Razvoj i odgovorna primena veb tehnologija, programiranja, platformi i aplikacija.</p></div><div class="service-card"><h3>Nauka i istraživanje</h3><p>Podrška istraživačkim, razvojnim i interdisciplinarnim aktivnostima.</p></div><div class="service-card"><h3>Javni interes</h3><p>Programi i projekti koji doprinose obrazovanju, inovacijama i društvenom napretku.</p></div><div class="service-card"><h3>Saradnja</h3><p>Povezivanje sa ustanovama, institucijama, privredom i organizacijama u zemlji i inostranstvu.</p></div></div></div></section>

<?php require __DIR__ . '/includes/footer.php'; ?>
