<?php
$page_title       = 'Projekti i aktivnosti';
$page_description = 'Programske celine, projekti i aktivnosti Udruženja „Mikiliks veb razvoja" u oblasti obrazovanja, nauke i digitalnog razvoja.';
require __DIR__ . '/includes/header.php';
?>

<section class="subhero"><div class="container"><div class="breadcrumbs"><a href="index.php">Početna</a> / Projekti</div><h1>Projekti i aktivnosti</h1><p class="lead">Realizovani i aktuelni programi, radionice, seminari, edukacije i razvojni poduhvati udruženja.</p></div></section>
<section class="section"><div class="container"><div class="center"><span class="eyebrow">Naš rad</span><h2>Programske celine</h2><p class="lead">Kroz stalne programske celine radimo na digitalnoj pismenosti, edukaciji dece i mladih i digitalizaciji organizacija — svaki projekat prati jasan cilj, partneri i merljivi rezultati.</p></div><div class="grid grid-3 projects"><article class="project-card"><div class="project-image"><img src="assets/img/project-digital.svg" alt="Digitalna pismenost"></div><div class="project-body"><div class="project-kicker">Aktuelni program</div><h3>Digitalna pismenost za građane</h3><p>Obuke za korišćenje digitalnih servisa, bezbednost na internetu, rad sa dokumentima i komunikacionim alatima.</p></div></article><article class="project-card"><div class="project-image"><img src="assets/img/project-edu.svg" alt="Edukacije"></div><div class="project-body"><div class="project-kicker">Edukacija</div><h3>Radionice za decu i mlade</h3><p>Uvod u programiranje, kreativno rešavanje problema, nauku i praktične digitalne veštine.</p></div></article><article class="project-card"><div class="project-image"><img src="assets/img/project-web.svg" alt="Veb podrška"></div><div class="project-body"><div class="project-kicker">Stručna podrška</div><h3>Digitalizacija organizacija</h3><p>Razvoj veb sajtova, formi, platformi, baza sadržaja i automatizovanih procesa za ustanove i udruženja.</p></div></article></div></div></section>
<section class="section soft"><div class="container grid grid-2"><div class="content-card"><span class="eyebrow">Trenutni projekti</span><h2 style="font-size:2rem">Aktivnosti u toku</h2><div class="loading-notice"><span class="spinner" aria-hidden="true"></span><span>Stranica je u pripremi — uskoro aktivni projekti.</span></div></div><div class="content-card"><span class="eyebrow">Realizovani projekti</span><h2 style="font-size:2rem">Arhiva rezultata</h2><div class="loading-notice"><span class="spinner" aria-hidden="true"></span><span>Stranica je u pripremi — uskoro arhiva rezultata.</span></div></div></div></section>
<section id="galerija" class="section"><div class="container"><div class="center"><span class="eyebrow">Galerija</span><h2>Fotografije sa događaja</h2><p class="lead">Utisci, trenuci i rezultati sa naših radionica, seminara, prezentacija i drugih aktivnosti.</p></div><div class="gallery-embed">
<!-- Elfsight Instagram Feed | Untitled Instagram Feed -->
<script src="https://elfsightcdn.com/platform.js" async></script>
<div class="elfsight-app-1d59c531-fc80-4bf1-b4e0-1c3831441d45" data-elfsight-app-lazy></div>
</div><div class="gallery-cta"><a href="https://www.instagram.com/udruzenjemikiliksvebrazvoj/" target="_blank" rel="noopener noreferrer" class="btn-ig-all"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><rect x="2" y="2" width="20" height="20" rx="6" stroke="currentColor" stroke-width="2"></rect><circle cx="12" cy="12" r="4.5" stroke="currentColor" stroke-width="2"></circle><circle cx="17.5" cy="6.5" r="1.2" fill="currentColor"></circle></svg>Pogledaj sve fotografije</a></div></div></section>
<style>
.gallery-cta{text-align:center;margin-top:28px}
.btn-ig-all{display:inline-flex;align-items:center;gap:10px;padding:12px 30px;background:#117fe8;color:#fff;font-weight:600;font-size:15px;border-radius:8px;text-decoration:none;transition:transform .2s ease,box-shadow .2s ease,background .2s ease}
.btn-ig-all:hover{background:#0d68c2;color:#fff;transform:translateY(-2px);box-shadow:0 10px 22px rgba(17,127,232,.30)}
</style>
<section class="section soft"><div class="container"><div class="center"><span class="eyebrow">Partneri</span><h2>Saradnja na projektima</h2></div><div class="partner-row"><span class="partner">Škole i fakulteti</span><span class="partner">Lokalne institucije</span><span class="partner">Kompanije</span><span class="partner">Fondacije</span><span class="partner">Udruženja</span><span class="partner">Međunarodni partneri</span></div></div></section>

<?php require __DIR__ . '/includes/footer.php'; ?>
