<?php
$page_title       = 'Projekti i aktivnosti';
$page_description = 'Programske celine, projekti i aktivnosti Udruženja „Mikiliks veb razvoja" u oblasti obrazovanja, nauke i digitalnog razvoja.';
require __DIR__ . '/includes/header.php';
?>

<section class="subhero"><div class="container"><div class="breadcrumbs"><a href="index.php">Početna</a> / Projekti</div><h1>Projekti i aktivnosti</h1><p class="lead">Realizovani i aktuelni programi, radionice, seminari, edukacije i razvojni poduhvati udruženja.</p></div></section>
<section class="section"><div class="container"><div class="center"><span class="eyebrow">Naš rad</span><h2>Programske celine</h2><p class="lead">Kroz stalne programske celine radimo na digitalnoj pismenosti, edukaciji dece i mladih i digitalizaciji organizacija — svaki projekat prati jasan cilj, partneri i merljivi rezultati.</p></div><div class="grid grid-3 projects"><article class="project-card"><div class="project-image"><img src="assets/img/project-digital.svg" alt="Digitalna pismenost"></div><div class="project-body"><div class="project-kicker">Aktuelni program</div><h3>Digitalna pismenost za građane</h3><p>Obuke za korišćenje digitalnih servisa, bezbednost na internetu, rad sa dokumentima i komunikacionim alatima.</p></div></article><article class="project-card"><div class="project-image"><img src="assets/img/project-edu.svg" alt="Edukacije"></div><div class="project-body"><div class="project-kicker">Edukacija</div><h3>Radionice za decu i mlade</h3><p>Uvod u programiranje, kreativno rešavanje problema, nauku i praktične digitalne veštine.</p></div></article><article class="project-card"><div class="project-image"><img src="assets/img/project-web.svg" alt="Veb podrška"></div><div class="project-body"><div class="project-kicker">Stručna podrška</div><h3>Digitalizacija organizacija</h3><p>Razvoj veb sajtova, formi, platformi, baza sadržaja i automatizovanih procesa za ustanove i udruženja.</p></div></article></div></div></section>
<section class="section soft"><div class="container grid grid-2"><div class="content-card"><span class="eyebrow">Trenutni projekti</span><h2 style="font-size:2rem">Aktivnosti u toku</h2><div class="loading-notice"><span class="spinner" aria-hidden="true"></span><span>Stranica je u pripremi — uskoro aktivni projekti.</span></div></div><div class="content-card"><span class="eyebrow">Realizovani projekti</span><h2 style="font-size:2rem">Arhiva rezultata</h2><div class="loading-notice"><span class="spinner" aria-hidden="true"></span><span>Stranica je u pripremi — uskoro arhiva rezultata.</span></div></div></div></section>
<section id="galerija" class="section"><div class="container"><div class="center"><span class="eyebrow">Galerija</span><h2>Fotografije sa događaja</h2><p class="lead">Utisci, trenuci i rezultati sa naših radionica, seminara, prezentacija i drugih aktivnosti.</p></div><div class="gallery cards"><div class="gallery-item">Fotografija događaja 01</div><div class="gallery-item">Fotografija događaja 02</div><div class="gallery-item">Fotografija događaja 03</div><div class="gallery-item">Radovi polaznika 01</div><div class="gallery-item">Radovi polaznika 02</div><div class="gallery-item">Partnerska aktivnost</div></div></div></section>
<section class="section soft"><div class="container"><div class="center"><span class="eyebrow">Partneri</span><h2>Saradnja na projektima</h2></div><div class="partner-row"><span class="partner">Škole i fakulteti</span><span class="partner">Lokalne institucije</span><span class="partner">Kompanije</span><span class="partner">Fondacije</span><span class="partner">Udruženja</span><span class="partner">Međunarodni partneri</span></div></div></section>

<?php require __DIR__ . '/includes/footer.php'; ?>
