<?php
$pageTitle = 'Vesti | Микиликс веб развој';
$pageDescription = 'Obaveštenja, najave i novosti iz rada Udruženja „Микиликс веб развој".';
$activePage = 'vesti';
require __DIR__ . '/includes/header.php';
?>

<section class="subhero"><div class="container"><div class="breadcrumbs"><a href="index.php">Početna</a> / Vesti</div><h1>Vesti</h1><p class="lead">Obaveštenja, izveštaji sa događaja, najave aktivnosti i novosti iz rada udruženja.</p></div></section>
<section class="section"><div class="container"><div class="grid grid-3"><article class="news-card"><div class="news-top"><span class="news-date">01. jun 2026.</span></div><div class="news-body"><div class="news-meta">Dokumenta</div><h3>Usvojen novi Statut udruženja</h3><p>Skupština je usvojila novi Statut sa proširenim ciljevima i aktivnostima u oblasti obrazovanja, nauke i IT-ja.</p><a class="more" href="dokumenta.php">Pročitajte više →</a></div></article><article class="news-card"><div class="news-top"><span class="news-date">Članstvo</span></div><div class="news-body"><div class="news-meta">Obaveštenje</div><h3>Online pristupnica je dostupna</h3><p>Zainteresovani građani mogu da popune podatke potrebne za pokretanje postupka učlanjenja.</p><a class="more" href="clanstvo.php">Prijavite se →</a></div></article><article class="news-card"><div class="news-top"><span class="news-date">U pripremi</span></div><div class="news-body"><div class="news-meta">Edukacije</div><h3>Najava novih radionica</h3><p>U pripremi je kalendar edukacija iz digitalne pismenosti, veb tehnologija i savremenih digitalnih alata.</p><a class="more" href="edukacije.php">Saznajte više →</a></div></article></div></div></section>
<section class="section soft"><div class="container grid grid-2"><div><span class="eyebrow">Za administratore</span><h2>Šta svaka vest treba da sadrži</h2><div class="check-list"><div class="check"><i>✓</i><span>Jasan naslov i datum objave</span></div><div class="check"><i>✓</i><span>Kratak uvod i detaljan opis aktivnosti</span></div><div class="check"><i>✓</i><span>Fotografiju ili vizuelni materijal</span></div><div class="check"><i>✓</i><span>Podatke o partnerima i rezultatima</span></div><div class="check"><i>✓</i><span>Dokument, prijavu ili kontakt kada je potreban</span></div></div></div><div class="content-card"><h3>Prijava za obaveštenja</h3><p>Forma za budući newsletter i najave događaja.</p><form class="form" data-demo-form><div class="field"><label for="news-email">E-mail adresa</label><input id="news-email" type="email" required placeholder="ime@domen.rs"></div><button class="btn btn-primary" type="submit">Prijavi me</button><div class="notice form-message" style="display:none"></div></form></div></div></section>

<?php require __DIR__ . '/includes/footer.php'; ?>
